
name: Release Workflow
on:
  create:
    tags:
      - 'v*'
  push:
    paths-ignore:
      - 'release_history.txt'

jobs:
  update_file:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Update release_history.txt
        run: |
          echo "....updating this file to understand GITHUB workflow as we have a new release tag" >> release_history.txt

      - name: Commit and push changes
        run: |
          git config --local user.email "sharanyachandranz@github.com"
          git config --local user.name "sharanyachandranz"
          git add .
          git commit -m "Update release_history.txt on release tag"
          git push --set-upstream origin
